
sshHost='deinmo.eu.pythonanywhere.com'
sshUser='deinmo'
sshPass='Python2024_@2#$_29_'
remoteH='deinmo.mysql.eu.pythonanywhere-services.com'
dbuser='deinmo'
dbpasswd='Mydb_2025'
db='deinmo$aviation'

host = "localhost"
user = "root"
password = "2023"
database = "aviationcity"